# Demo

This notebook is the demo of our foward and viterbi algorithm on protein sequence recovery. Transition, emission, and initial probabilities are copied directly from "Transition & Emission Matrix" notebook.

In [1]:
transition_prob = {'-': {'-': 0.8407079646017699,
  'a': 0.0,
  'c': 0.0,
  'd': 0.008849557522123894,
  'e': 0.008849557522123894,
  'f': 0.017699115044247787,
  'g': 0.008849557522123894,
  'h': 0.04424778761061947,
  'i': 0.0,
  'k': 0.008849557522123894,
  'l': 0.0,
  'm': 0.035398230088495575,
  'n': 0.008849557522123894,
  'p': 0.0,
  'q': 0.0,
  'r': 0.0,
  's': 0.008849557522123894,
  't': 0.008849557522123894,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 'a': {'-': 0.003067484662576687,
  'a': 0.1196319018404908,
  'c': 0.02147239263803681,
  'd': 0.03680981595092025,
  'e': 0.05214723926380368,
  'f': 0.06748466257668712,
  'g': 0.009202453987730062,
  'h': 0.03067484662576687,
  'i': 0.03987730061349693,
  'k': 0.07668711656441718,
  'l': 0.12883435582822086,
  'm': 0.024539877300613498,
  'n': 0.018404907975460124,
  'p': 0.015337423312883436,
  'q': 0.015337423312883436,
  'r': 0.02147239263803681,
  's': 0.12269938650306748,
  't': 0.05828220858895705,
  'v': 0.09815950920245399,
  'w': 0.0,
  'y': 0.03987730061349693},
 'c': {'-': 0.0,
  'a': 0.058394160583941604,
  'c': 0.0072992700729927005,
  'd': 0.0,
  'e': 0.043795620437956206,
  'f': 0.021897810218978103,
  'g': 0.06569343065693431,
  'h': 0.0072992700729927005,
  'i': 0.0072992700729927005,
  'k': 0.10948905109489052,
  'l': 0.145985401459854,
  'm': 0.18248175182481752,
  'n': 0.0072992700729927005,
  'p': 0.072992700729927,
  'q': 0.051094890510948905,
  'r': 0.072992700729927,
  's': 0.051094890510948905,
  't': 0.0948905109489051,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 'd': {'-': 0.02040816326530612,
  'a': 0.053061224489795916,
  'c': 0.004081632653061225,
  'd': 0.024489795918367346,
  'e': 0.08979591836734693,
  'f': 0.0326530612244898,
  'g': 0.044897959183673466,
  'h': 0.05714285714285714,
  'i': 0.1346938775510204,
  'k': 0.08163265306122448,
  'l': 0.06938775510204082,
  'm': 0.0163265306122449,
  'n': 0.08163265306122448,
  'p': 0.0,
  'q': 0.02040816326530612,
  'r': 0.0326530612244898,
  's': 0.0653061224489796,
  't': 0.08163265306122448,
  'v': 0.02040816326530612,
  'w': 0.0,
  'y': 0.06938775510204082},
 'e': {'-': 0.0061162079510703364,
  'a': 0.01834862385321101,
  'c': 0.03363914373088685,
  'd': 0.07951070336391437,
  'e': 0.04281345565749235,
  'f': 0.024464831804281346,
  'g': 0.10091743119266056,
  'h': 0.024464831804281346,
  'i': 0.0764525993883792,
  'k': 0.0581039755351682,
  'l': 0.13149847094801223,
  'm': 0.05198776758409786,
  'n': 0.05198776758409786,
  'p': 0.039755351681957186,
  'q': 0.01834862385321101,
  'r': 0.01529051987767584,
  's': 0.024464831804281346,
  't': 0.06116207951070336,
  'v': 0.07339449541284404,
  'w': 0.01529051987767584,
  'y': 0.05198776758409786},
 'f': {'-': 0.003937007874015748,
  'a': 0.07086614173228346,
  'c': 0.015748031496062992,
  'd': 0.015748031496062992,
  'e': 0.027559055118110236,
  'f': 0.027559055118110236,
  'g': 0.05511811023622047,
  'h': 0.015748031496062992,
  'i': 0.03937007874015748,
  'k': 0.05905511811023622,
  'l': 0.2440944881889764,
  'm': 0.023622047244094488,
  'n': 0.04330708661417323,
  'p': 0.015748031496062992,
  'q': 0.047244094488188976,
  'r': 0.03543307086614173,
  's': 0.06692913385826772,
  't': 0.05511811023622047,
  'v': 0.09055118110236221,
  'w': 0.003937007874015748,
  'x': 0.003937007874015748,
  'y': 0.03937007874015748},
 'g': {'-': 0.0,
  'a': 0.16363636363636364,
  'c': 0.02181818181818182,
  'd': 0.09818181818181818,
  'e': 0.05090909090909091,
  'f': 0.03636363636363636,
  'g': 0.025454545454545455,
  'h': 0.04,
  'i': 0.03272727272727273,
  'k': 0.03636363636363636,
  'l': 0.06909090909090909,
  'm': 0.04,
  'n': 0.09454545454545454,
  'p': 0.0036363636363636364,
  'q': 0.02181818181818182,
  'r': 0.05818181818181818,
  's': 0.05090909090909091,
  't': 0.01090909090909091,
  'v': 0.06909090909090909,
  'w': 0.01818181818181818,
  'y': 0.05818181818181818},
 'h': {'-': 0.017316017316017316,
  'a': 0.09090909090909091,
  'c': 0.021645021645021644,
  'd': 0.03463203463203463,
  'e': 0.05627705627705628,
  'f': 0.08225108225108226,
  'g': 0.06493506493506493,
  'h': 0.06493506493506493,
  'i': 0.12554112554112554,
  'k': 0.004329004329004329,
  'l': 0.08658008658008658,
  'm': 0.025974025974025976,
  'n': 0.0735930735930736,
  'p': 0.025974025974025976,
  'q': 0.021645021645021644,
  'r': 0.03896103896103896,
  's': 0.05627705627705628,
  't': 0.030303030303030304,
  'v': 0.012987012987012988,
  'w': 0.017316017316017316,
  'y': 0.047619047619047616},
 'i': {'-': 0.002967359050445104,
  'a': 0.0771513353115727,
  'c': 0.0,
  'd': 0.005934718100890208,
  'e': 0.05341246290801187,
  'f': 0.08011869436201781,
  'g': 0.01483679525222552,
  'h': 0.020771513353115726,
  'i': 0.09792284866468842,
  'k': 0.09495548961424333,
  'l': 0.12166172106824925,
  'm': 0.005934718100890208,
  'n': 0.09198813056379822,
  'p': 0.03560830860534125,
  'q': 0.050445103857566766,
  'r': 0.02373887240356083,
  's': 0.06824925816023739,
  't': 0.020771513353115726,
  'v': 0.10682492581602374,
  'w': 0.002967359050445104,
  'y': 0.02373887240356083},
 'k': {'-': 0.0,
  'a': 0.02956989247311828,
  'c': 0.051075268817204304,
  'd': 0.06720430107526881,
  'e': 0.07795698924731183,
  'f': 0.026881720430107527,
  'g': 0.04032258064516129,
  'h': 0.02956989247311828,
  'i': 0.016129032258064516,
  'k': 0.08870967741935484,
  'l': 0.06989247311827956,
  'm': 0.03763440860215054,
  'n': 0.0456989247311828,
  'p': 0.021505376344086023,
  'q': 0.051075268817204304,
  'r': 0.06451612903225806,
  's': 0.07258064516129033,
  't': 0.02956989247311828,
  'v': 0.10752688172043011,
  'w': 0.03763440860215054,
  'y': 0.03494623655913978},
 'l': {'-': 0.0,
  'a': 0.04843304843304843,
  'c': 0.009971509971509971,
  'd': 0.037037037037037035,
  'e': 0.07834757834757834,
  'f': 0.03133903133903134,
  'g': 0.037037037037037035,
  'h': 0.11396011396011396,
  'i': 0.05555555555555555,
  'k': 0.06552706552706553,
  'l': 0.1737891737891738,
  'm': 0.03561253561253561,
  'n': 0.0584045584045584,
  'p': 0.024216524216524215,
  'q': 0.04985754985754986,
  'r': 0.042735042735042736,
  's': 0.06267806267806268,
  't': 0.03133903133903134,
  'v': 0.029914529914529916,
  'w': 0.005698005698005698,
  'y': 0.008547008547008548},
 'm': {'-': 0.0,
  'a': 0.06372549019607843,
  'c': 0.024509803921568627,
  'd': 0.06372549019607843,
  'e': 0.08333333333333333,
  'f': 0.024509803921568627,
  'g': 0.024509803921568627,
  'h': 0.0196078431372549,
  'i': 0.10784313725490197,
  'k': 0.12745098039215685,
  'l': 0.08823529411764706,
  'm': 0.06862745098039216,
  'n': 0.0784313725490196,
  'p': 0.00980392156862745,
  'q': 0.07352941176470588,
  'r': 0.00980392156862745,
  's': 0.014705882352941176,
  't': 0.058823529411764705,
  'v': 0.049019607843137254,
  'w': 0.0,
  'y': 0.00980392156862745},
 'n': {'-': 0.0058309037900874635,
  'a': 0.04956268221574344,
  'c': 0.014577259475218658,
  'd': 0.014577259475218658,
  'e': 0.052478134110787174,
  'f': 0.07580174927113703,
  'g': 0.08163265306122448,
  'h': 0.043731778425655975,
  'i': 0.061224489795918366,
  'k': 0.0728862973760933,
  'l': 0.12244897959183673,
  'm': 0.014577259475218658,
  'n': 0.0641399416909621,
  'p': 0.014577259475218658,
  'q': 0.023323615160349854,
  'r': 0.043731778425655975,
  's': 0.0728862973760933,
  't': 0.0728862973760933,
  'v': 0.052478134110787174,
  'w': 0.0029154518950437317,
  'y': 0.043731778425655975},
 'p': {'-': 0.005714285714285714,
  'a': 0.04,
  'c': 0.011428571428571429,
  'd': 0.005714285714285714,
  'e': 0.06857142857142857,
  'f': 0.02857142857142857,
  'g': 0.03428571428571429,
  'h': 0.005714285714285714,
  'i': 0.09142857142857143,
  'k': 0.005714285714285714,
  'l': 0.36,
  'm': 0.03428571428571429,
  'n': 0.08,
  'p': 0.0,
  'q': 0.017142857142857144,
  'r': 0.03428571428571429,
  's': 0.04,
  't': 0.022857142857142857,
  'v': 0.09142857142857143,
  'w': 0.0,
  'y': 0.022857142857142857},
 'q': {'-': 0.00425531914893617,
  'a': 0.0425531914893617,
  'c': 0.05106382978723404,
  'd': 0.08085106382978724,
  'e': 0.05106382978723404,
  'f': 0.01276595744680851,
  'g': 0.10212765957446808,
  'h': 0.06382978723404255,
  'i': 0.03829787234042553,
  'k': 0.10638297872340426,
  'l': 0.059574468085106386,
  'm': 0.03404255319148936,
  'n': 0.01702127659574468,
  'p': 0.03404255319148936,
  'q': 0.05531914893617021,
  'r': 0.05531914893617021,
  's': 0.0425531914893617,
  't': 0.05106382978723404,
  'v': 0.07234042553191489,
  'w': 0.02127659574468085,
  'y': 0.00425531914893617},
 'r': {'-': 0.0,
  'a': 0.050761421319796954,
  'c': 0.025380710659898477,
  'd': 0.04568527918781726,
  'e': 0.030456852791878174,
  'f': 0.03553299492385787,
  'g': 0.025380710659898477,
  'h': 0.01015228426395939,
  'i': 0.07614213197969544,
  'k': 0.08121827411167512,
  'l': 0.16751269035532995,
  'm': 0.015228426395939087,
  'n': 0.09644670050761421,
  'p': 0.06091370558375635,
  'q': 0.06091370558375635,
  'r': 0.015228426395939087,
  's': 0.10152284263959391,
  't': 0.01015228426395939,
  'v': 0.015228426395939087,
  'w': 0.03553299492385787,
  'x': 0.005076142131979695,
  'y': 0.03553299492385787},
 's': {'-': 0.0029239766081871343,
  'a': 0.023391812865497075,
  'c': 0.03216374269005848,
  'd': 0.04093567251461988,
  'e': 0.043859649122807015,
  'f': 0.07309941520467836,
  'g': 0.05263157894736842,
  'h': 0.029239766081871343,
  'i': 0.06725146198830409,
  'k': 0.08187134502923976,
  'l': 0.09064327485380116,
  'm': 0.02631578947368421,
  'n': 0.038011695906432746,
  'p': 0.07894736842105263,
  'q': 0.02046783625730994,
  'r': 0.023391812865497075,
  's': 0.06725146198830409,
  't': 0.08187134502923976,
  'v': 0.043859649122807015,
  'w': 0.014619883040935672,
  'x': 0.0029239766081871343,
  'y': 0.06432748538011696},
 't': {'-': 0.0,
  'a': 0.08984375,
  'c': 0.046875,
  'd': 0.06640625,
  'e': 0.08203125,
  'f': 0.0390625,
  'g': 0.04296875,
  'h': 0.0234375,
  'i': 0.0390625,
  'k': 0.05078125,
  'l': 0.06640625,
  'm': 0.046875,
  'n': 0.0625,
  'p': 0.0703125,
  'q': 0.0625,
  'r': 0.03515625,
  's': 0.06640625,
  't': 0.0625,
  'v': 0.03125,
  'w': 0.0,
  'y': 0.015625},
 'v': {'-': 0.0,
  'a': 0.018633540372670808,
  'c': 0.031055900621118012,
  'd': 0.062111801242236024,
  'e': 0.06521739130434782,
  'f': 0.06832298136645963,
  'g': 0.034161490683229816,
  'h': 0.021739130434782608,
  'i': 0.052795031055900624,
  'k': 0.059006211180124224,
  'l': 0.13043478260869565,
  'm': 0.055900621118012424,
  'n': 0.08074534161490683,
  'p': 0.037267080745341616,
  'q': 0.11180124223602485,
  'r': 0.006211180124223602,
  's': 0.052795031055900624,
  't': 0.009316770186335404,
  'v': 0.07453416149068323,
  'w': 0.0,
  'y': 0.027950310559006212},
 'w': {'-': 0.0,
  'a': 0.08620689655172414,
  'c': 0.06896551724137931,
  'd': 0.08620689655172414,
  'e': 0.017241379310344827,
  'f': 0.05172413793103448,
  'g': 0.10344827586206896,
  'h': 0.0,
  'i': 0.034482758620689655,
  'k': 0.017241379310344827,
  'l': 0.034482758620689655,
  'm': 0.08620689655172414,
  'n': 0.1724137931034483,
  'p': 0.0,
  'q': 0.08620689655172414,
  'r': 0.0,
  's': 0.0,
  't': 0.10344827586206896,
  'v': 0.034482758620689655,
  'w': 0.0,
  'y': 0.017241379310344827},
 'x': {'-': 0.0,
  'a': 0.0,
  'c': 0.0,
  'd': 0.3333333333333333,
  'e': 0.0,
  'f': 0.3333333333333333,
  'g': 0.0,
  'h': 0.0,
  'i': 0.0,
  'k': 0.0,
  'l': 0.0,
  'm': 0.0,
  'n': 0.3333333333333333,
  'p': 0.0,
  'q': 0.0,
  'r': 0.0,
  's': 0.0,
  't': 0.0,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 'y': {'-': 0.0,
  'a': 0.03409090909090909,
  'c': 0.056818181818181816,
  'd': 0.022727272727272728,
  'e': 0.045454545454545456,
  'f': 0.05113636363636364,
  'g': 0.125,
  'h': 0.028409090909090908,
  'i': 0.022727272727272728,
  'k': 0.005681818181818182,
  'l': 0.1590909090909091,
  'm': 0.005681818181818182,
  'n': 0.07954545454545454,
  'p': 0.08522727272727272,
  'q': 0.017045454545454544,
  'r': 0.07386363636363637,
  's': 0.056818181818181816,
  't': 0.0625,
  'v': 0.03409090909090909,
  'w': 0.03409090909090909,
  'y': 0.0}}

In [2]:
emission_prob = {'-': {'-': 0.0,
  'a': 0.006369426751592357,
  'c': 0.07006369426751592,
  'd': 0.012738853503184714,
  'e': 0.03184713375796178,
  'f': 0.08917197452229299,
  'g': 0.03821656050955414,
  'h': 0.0,
  'i': 0.12101910828025478,
  'k': 0.06369426751592357,
  'l': 0.08280254777070063,
  'm': 0.03184713375796178,
  'n': 0.03184713375796178,
  'p': 0.025477707006369428,
  'q': 0.08280254777070063,
  'r': 0.0,
  's': 0.10828025477707007,
  't': 0.025477707006369428,
  'v': 0.12101910828025478,
  'w': 0.0,
  'y': 0.05732484076433121},
 'a': {'-': 0.005970149253731343,
  'a': 0.8686567164179104,
  'c': 0.0,
  'd': 0.0,
  'e': 0.0029850746268656717,
  'f': 0.0,
  'g': 0.023880597014925373,
  'h': 0.0029850746268656717,
  'i': 0.0029850746268656717,
  'k': 0.01791044776119403,
  'l': 0.0029850746268656717,
  'm': 0.0,
  'n': 0.0,
  'p': 0.0029850746268656717,
  'q': 0.0029850746268656717,
  'r': 0.0029850746268656717,
  's': 0.01791044776119403,
  't': 0.029850746268656716,
  'v': 0.014925373134328358,
  'w': 0.0,
  'y': 0.0},
 'c': {'-': 0.041379310344827586,
  'a': 0.0,
  'c': 0.7655172413793103,
  'd': 0.006896551724137931,
  'e': 0.006896551724137931,
  'f': 0.0,
  'g': 0.0,
  'h': 0.006896551724137931,
  'i': 0.006896551724137931,
  'k': 0.0,
  'l': 0.013793103448275862,
  'm': 0.0,
  'n': 0.0,
  'p': 0.0,
  'q': 0.0,
  'r': 0.0,
  's': 0.0896551724137931,
  't': 0.0,
  'v': 0.0,
  'w': 0.041379310344827586,
  'y': 0.020689655172413793},
 'd': {'-': 0.045283018867924525,
  'a': 0.0,
  'c': 0.0037735849056603774,
  'd': 0.7924528301886793,
  'e': 0.07169811320754717,
  'f': 0.0037735849056603774,
  'g': 0.0037735849056603774,
  'h': 0.007547169811320755,
  'i': 0.0,
  'k': 0.0037735849056603774,
  'l': 0.0,
  'm': 0.0,
  'n': 0.03773584905660377,
  'p': 0.0037735849056603774,
  'q': 0.0,
  'r': 0.0,
  's': 0.01509433962264151,
  't': 0.0037735849056603774,
  'v': 0.007547169811320755,
  'w': 0.0,
  'y': 0.0},
 'e': {'-': 0.01791044776119403,
  'a': 0.011940298507462687,
  'c': 0.0,
  'd': 0.03880597014925373,
  'e': 0.826865671641791,
  'f': 0.0,
  'g': 0.008955223880597015,
  'h': 0.0029850746268656717,
  'i': 0.0,
  'k': 0.020895522388059702,
  'l': 0.008955223880597015,
  'm': 0.0,
  'n': 0.01791044776119403,
  'p': 0.0,
  'q': 0.029850746268656716,
  'r': 0.0029850746268656717,
  's': 0.0029850746268656717,
  't': 0.008955223880597015,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 'f': {'-': 0.021367521367521368,
  'a': 0.008547008547008548,
  'c': 0.004273504273504274,
  'd': 0.0,
  'e': 0.0,
  'f': 0.8632478632478633,
  'g': 0.0,
  'h': 0.0,
  'i': 0.01282051282051282,
  'k': 0.0,
  'l': 0.0641025641025641,
  'm': 0.0,
  'n': 0.0,
  'p': 0.0,
  'q': 0.0,
  'r': 0.004273504273504274,
  's': 0.008547008547008548,
  't': 0.0,
  'v': 0.0,
  'w': 0.0,
  'x': 0.004273504273504274,
  'y': 0.008547008547008548},
 'g': {'-': 0.03214285714285714,
  'a': 0.014285714285714285,
  'c': 0.0,
  'd': 0.014285714285714285,
  'e': 0.025,
  'f': 0.0,
  'g': 0.8642857142857143,
  'h': 0.0035714285714285713,
  'i': 0.0035714285714285713,
  'k': 0.0035714285714285713,
  'l': 0.0,
  'm': 0.0,
  'n': 0.007142857142857143,
  'p': 0.0,
  'q': 0.0,
  'r': 0.0035714285714285713,
  's': 0.02142857142857143,
  't': 0.0,
  'v': 0.007142857142857143,
  'w': 0.0,
  'y': 0.0},
 'h': {'-': 0.02608695652173913,
  'a': 0.0,
  'c': 0.0,
  'd': 0.0,
  'e': 0.004347826086956522,
  'f': 0.004347826086956522,
  'g': 0.004347826086956522,
  'h': 0.8478260869565217,
  'i': 0.0,
  'k': 0.0,
  'l': 0.0,
  'm': 0.0,
  'n': 0.0391304347826087,
  'p': 0.0,
  'q': 0.0391304347826087,
  'r': 0.004347826086956522,
  's': 0.008695652173913044,
  't': 0.0,
  'v': 0.0,
  'w': 0.0,
  'y': 0.021739130434782608},
 'i': {'-': 0.021212121212121213,
  'a': 0.00909090909090909,
  'c': 0.0,
  'd': 0.0,
  'e': 0.0030303030303030303,
  'f': 0.015151515151515152,
  'g': 0.0,
  'h': 0.0,
  'i': 0.803030303030303,
  'k': 0.0,
  'l': 0.03939393939393939,
  'm': 0.021212121212121213,
  'n': 0.0,
  'p': 0.0030303030303030303,
  'q': 0.0,
  'r': 0.0,
  's': 0.0030303030303030303,
  't': 0.024242424242424242,
  'v': 0.05454545454545454,
  'w': 0.0,
  'x': 0.0030303030303030303,
  'y': 0.0},
 'k': {'-': 0.011594202898550725,
  'a': 0.0,
  'c': 0.0,
  'd': 0.005797101449275362,
  'e': 0.008695652173913044,
  'f': 0.0,
  'g': 0.008695652173913044,
  'h': 0.005797101449275362,
  'i': 0.002898550724637681,
  'k': 0.8521739130434782,
  'l': 0.0,
  'm': 0.0,
  'n': 0.020289855072463767,
  'p': 0.0,
  'q': 0.028985507246376812,
  'r': 0.034782608695652174,
  's': 0.008695652173913044,
  't': 0.011594202898550725,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 'l': {'-': 0.012857142857142857,
  'a': 0.002857142857142857,
  'c': 0.0014285714285714286,
  'd': 0.0,
  'e': 0.0,
  'f': 0.017142857142857144,
  'g': 0.0,
  'h': 0.0,
  'i': 0.018571428571428572,
  'k': 0.0,
  'l': 0.8928571428571429,
  'm': 0.011428571428571429,
  'n': 0.0014285714285714286,
  'p': 0.0014285714285714286,
  'q': 0.002857142857142857,
  'r': 0.005714285714285714,
  's': 0.0014285714285714286,
  't': 0.005714285714285714,
  'v': 0.02142857142857143,
  'w': 0.0014285714285714286,
  'y': 0.0014285714285714286},
 'm': {'-': 0.02127659574468085,
  'a': 0.00851063829787234,
  'c': 0.0,
  'd': 0.0,
  'e': 0.00425531914893617,
  'f': 0.01276595744680851,
  'g': 0.00425531914893617,
  'h': 0.0,
  'i': 0.029787234042553193,
  'k': 0.00851063829787234,
  'l': 0.07234042553191489,
  'm': 0.7531914893617021,
  'n': 0.0,
  'p': 0.0,
  'q': 0.0,
  'r': 0.00851063829787234,
  's': 0.00851063829787234,
  't': 0.03404255319148936,
  'v': 0.03404255319148936,
  'w': 0.0,
  'y': 0.0},
 'n': {'-': 0.002898550724637681,
  'a': 0.0,
  'c': 0.008695652173913044,
  'd': 0.020289855072463767,
  'e': 0.0,
  'f': 0.002898550724637681,
  'g': 0.014492753623188406,
  'h': 0.020289855072463767,
  'i': 0.0,
  'k': 0.014492753623188406,
  'l': 0.0,
  'm': 0.0,
  'n': 0.8434782608695652,
  'p': 0.0,
  'q': 0.002898550724637681,
  'r': 0.008695652173913044,
  's': 0.05217391304347826,
  't': 0.0,
  'v': 0.0,
  'w': 0.002898550724637681,
  'y': 0.005797101449275362},
 'p': {'-': 0.02857142857142857,
  'a': 0.017142857142857144,
  'c': 0.0,
  'd': 0.0,
  'e': 0.0,
  'f': 0.0,
  'g': 0.0,
  'h': 0.011428571428571429,
  'i': 0.0,
  'k': 0.0,
  'l': 0.0,
  'm': 0.0,
  'n': 0.0,
  'p': 0.92,
  'q': 0.005714285714285714,
  'r': 0.0,
  's': 0.017142857142857144,
  't': 0.0,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 'q': {'-': 0.00975609756097561,
  'a': 0.0,
  'c': 0.004878048780487805,
  'd': 0.004878048780487805,
  'e': 0.00975609756097561,
  'f': 0.0,
  'g': 0.0,
  'h': 0.03902439024390244,
  'i': 0.0,
  'k': 0.05365853658536585,
  'l': 0.004878048780487805,
  'm': 0.0,
  'n': 0.0,
  'p': 0.0,
  'q': 0.848780487804878,
  'r': 0.01951219512195122,
  's': 0.0,
  't': 0.0,
  'v': 0.0,
  'w': 0.0,
  'x': 0.004878048780487805,
  'y': 0.0},
 'r': {'-': 0.034782608695652174,
  'a': 0.0,
  'c': 0.008695652173913044,
  'd': 0.0,
  'e': 0.004347826086956522,
  'f': 0.0,
  'g': 0.013043478260869565,
  'h': 0.0,
  'i': 0.008695652173913044,
  'k': 0.1391304347826087,
  'l': 0.004347826086956522,
  'm': 0.004347826086956522,
  'n': 0.008695652173913044,
  'p': 0.004347826086956522,
  'q': 0.0391304347826087,
  'r': 0.7130434782608696,
  's': 0.004347826086956522,
  't': 0.004347826086956522,
  'v': 0.0,
  'w': 0.004347826086956522,
  'y': 0.004347826086956522},
 's': {'-': 0.043333333333333335,
  'a': 0.02,
  'c': 0.01,
  'd': 0.016666666666666666,
  'e': 0.013333333333333334,
  'f': 0.0033333333333333335,
  'g': 0.0033333333333333335,
  'h': 0.0033333333333333335,
  'i': 0.013333333333333334,
  'k': 0.006666666666666667,
  'l': 0.0033333333333333335,
  'm': 0.0,
  'n': 0.023333333333333334,
  'p': 0.0033333333333333335,
  'q': 0.01,
  'r': 0.006666666666666667,
  's': 0.8,
  't': 0.02,
  'v': 0.0,
  'w': 0.0,
  'y': 0.0},
 't': {'-': 0.023529411764705882,
  'a': 0.011764705882352941,
  'c': 0.00392156862745098,
  'd': 0.0,
  'e': 0.00784313725490196,
  'f': 0.00784313725490196,
  'g': 0.00392156862745098,
  'h': 0.00392156862745098,
  'i': 0.0196078431372549,
  'k': 0.00392156862745098,
  'l': 0.0,
  'm': 0.011764705882352941,
  'n': 0.00392156862745098,
  'p': 0.00392156862745098,
  'q': 0.00392156862745098,
  'r': 0.0,
  's': 0.08235294117647059,
  't': 0.8,
  'v': 0.00784313725490196,
  'w': 0.0,
  'y': 0.0},
 'v': {'-': 0.019672131147540985,
  'a': 0.01639344262295082,
  'c': 0.0,
  'd': 0.0,
  'e': 0.006557377049180328,
  'f': 0.009836065573770493,
  'g': 0.0,
  'h': 0.003278688524590164,
  'i': 0.04918032786885246,
  'k': 0.0,
  'l': 0.03278688524590164,
  'm': 0.009836065573770493,
  'n': 0.003278688524590164,
  'p': 0.009836065573770493,
  'q': 0.003278688524590164,
  'r': 0.003278688524590164,
  's': 0.0,
  't': 0.009836065573770493,
  'v': 0.8229508196721311,
  'w': 0.0,
  'y': 0.0},
 'w': {'-': 0.0,
  'a': 0.0,
  'c': 0.02,
  'd': 0.0,
  'e': 0.0,
  'f': 0.0,
  'g': 0.0,
  'h': 0.0,
  'i': 0.0,
  'k': 0.0,
  'l': 0.0,
  'm': 0.0,
  'n': 0.0,
  'p': 0.0,
  'q': 0.0,
  'r': 0.0,
  's': 0.0,
  't': 0.0,
  'v': 0.0,
  'w': 0.98,
  'y': 0.0},
 'y': {'-': 0.011428571428571429,
  'a': 0.0,
  'c': 0.005714285714285714,
  'd': 0.0,
  'e': 0.0,
  'f': 0.05142857142857143,
  'g': 0.0,
  'h': 0.045714285714285714,
  'i': 0.0,
  'k': 0.0,
  'l': 0.0,
  'm': 0.0,
  'n': 0.005714285714285714,
  'p': 0.0,
  'q': 0.0,
  'r': 0.0,
  's': 0.005714285714285714,
  't': 0.0,
  'v': 0.0,
  'w': 0.0,
  'y': 0.8742857142857143}}

In [3]:
# Mouse sequence -> hidden states
# Other sequence -> observations
# TODO: USE MOUSE SEQUENCE FIND INITIAL_PROB
initial_prob = {'-': 0.027881370982063575,
 'a': 0.05949209731841591,
 'c': 0.02575031077961286,
 'd': 0.04706091280412005,
 'e': 0.05949209731841591,
 'f': 0.04155567394778902,
 'g': 0.04972473805718345,
 'h': 0.04084532054697212,
 'i': 0.05860415556739478,
 'k': 0.06126798082045818,
 'l': 0.12431184514295862,
 'm': 0.04173326229799325,
 'n': 0.06126798082045818,
 'p': 0.031077961285739655,
 'q': 0.03640561179186645,
 'r': 0.04084532054697212,
 's': 0.05327650506126798,
 't': 0.045285029302077784,
 'v': 0.054164446812289116,
 'w': 0.00887941751021133,
 'y': 0.031077961285739655}

In [4]:
import numpy as np
# obs {Array} - the observation sequence
# ep {nested dictionary} - emission probabilities
# tp {nested dictionary} - transition probabilities
# ip {dictioanry} - initial probabilties
# be able to return the joint probability of o_1:t and h_t
def forward(obs, ep, tp, ip):
    num_obs = len(obs)
    states = [s for s in emission_prob.keys()]
    num_states = len(states)
    
    
    # use a numpy matrix as a 2-D array to store probabilities
    mat = np.zeros((num_states, num_obs))

    # initialize the first column
    first_ob = obs[0]
    for i in range(num_states):
        mat[i, 0] = ip[first_ob] * ep[states[i]][first_ob]

    # compute the following columns recursively
    for i in range(1, num_obs):
        cur_obs = obs[i]
        for j in range(num_states): # current hidden state s_j
            summ = 0.0
            for k in range(num_states): # previous hidden state s_k
                #print("i: ",i, "j: ", j, "k: ",k)
                summ += mat[k, i-1] * ep[states[j]][cur_obs] * tp[states[k]][states[j]]
            mat[j, i] = summ
    
    # give out the predicted sequence
    predicted_seq = []
    for i in range(len(obs)):
      cur_max = -1
      index = -1
      for j in range(len(states)):
        if mat[j, i] > cur_max:
          cur_max = mat[j,i]
          index = j
      predicted_seq.append(states[index])
    
    return mat, predicted_seq

In [5]:
def viterbi(transition_matrix, emission_matrix, initial_prob, observations):
    # Initialize returning objects
    prediction_seq = []
    prediction_prob = 0
    # Initialize a dictionary for scores of each states
    scores = {i : [] for i in list(transition_matrix.keys())}
    # Fill in first scores column (start state to transition states probability)
    max_score = 0
    best_key = ''
    for key in scores:
        if key in emission_matrix or key in initial_prob:
          curr_observation = observations[0]
          score = emission_matrix[key][curr_observation]*initial_prob[key]
          scores[key].append(score)
          if score > max_score:
              max_score = score
              best_key = key
        else:
          scores[key].append(0.0)
    prediction_seq.append(best_key)
    # Update the rest of the scores
    for i in range(1, len(observations)): # For every column
        curr_observation = observations[i]
        for key in scores: # For every row
          if key in emission_matrix:
              state_scores = []
              for key2 in scores: # Finds all the cross probabilities
                  previous_score = scores[key2][i-1]
                  state_scores.append(previous_score*transition_matrix[key2][key]*emission_matrix[key][curr_observation])
              scores[key].append(max(state_scores))
          else:
            scores[key].append(0.0)
        # Adds the state to the prediction sequence
        max_score = 0
        best_key = ''
        for key in scores:
            score = scores[key][i]
            if score > max_score:
                max_score = score
                best_key = key
        prediction_seq.append(best_key)
    for key in scores:
        prob = scores[key][-1]
        if prob > prediction_prob:
            prediction_prob = prob
    #print(scores)
    return prediction_seq, prediction_prob

In [7]:
# TEST CASE WHETHER THE CODE WORKS
observe = ['a','c','y', '-']
def RunPredict(obs):
  res1= forward(obs, emission_prob, transition_prob, initial_prob)
  print("Forward Algorithm")
  print("The transition matrix: ", res1[0])
  print("The predicted Sequence: ", res1[1])
  res2 = viterbi(transition_prob, emission_prob, initial_prob, obs)
  print()
  print("Viterbi Algorithm")
  print("The transition matrix: ", res2[0])
  print("The predicted Sequence: ", res2[1])
RunPredict(observe)

Forward Algorithm
The transition matrix:  [[3.78930556e-04 3.46360108e-05 1.69965617e-06 0.00000000e+00]
 [5.16782099e-02 0.00000000e+00 0.00000000e+00 1.78177472e-09]
 [0.00000000e+00 9.85394754e-04 2.46911954e-07 1.50970113e-08]
 [0.00000000e+00 8.51664250e-06 0.00000000e+00 8.66413747e-09]
 [7.10353401e-04 0.00000000e+00 0.00000000e+00 6.37698701e-09]
 [5.08479464e-04 1.63574696e-05 2.63536153e-07 8.56240968e-09]
 [8.49887105e-04 0.00000000e+00 0.00000000e+00 2.69576978e-08]
 [0.00000000e+00 0.00000000e+00 3.12673749e-07 7.96922205e-09]
 [5.40837248e-04 0.00000000e+00 0.00000000e+00 4.91394996e-09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.65063530e-09]
 [1.69977421e-04 1.10326874e-05 2.33160331e-07 1.52671389e-08]
 [5.06315722e-04 0.00000000e+00 0.00000000e+00 3.58175914e-09]
 [0.00000000e+00 1.25433842e-05 9.34927261e-08 1.67872765e-09]
 [1.01986453e-03 0.00000000e+00 0.00000000e+00 1.62181101e-08]
 [0.00000000e+00 5.44300096e-06 0.00000000e+00 1.63981294e-09]
 [0.00000000e